apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim #Name of PVC
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default